# Generated by Django 2.2.6 on 2019-10-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('permiso', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('fecha_ini', models.DateField()),
                ('fecha_mod', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('fase', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('cod_lb', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto', unique=True)),
            ],
        ),
    ]
