# Generated by Django 2.2.6 on 2019-10-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20191025_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineabase',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
    ]
