# Generated by Django 2.2.6 on 2019-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20191025_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('dependencia', models.CharField(blank=True, max_length=50)),
                ('prioridad', models.CharField(blank=True, max_length=50)),
                ('fecha_ini', models.DateField()),
                ('fecha_mod', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='lineabase',
            old_name='cod_lb',
            new_name='id_lb',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_mod',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='cod_rol',
            new_name='id_rol',
        ),
    ]
