# Generated by Django 2.2.6 on 2019-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20191025_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fecha_mod',
            field=models.DateTimeField(),
        ),
    ]
