# Generated by Django 2.2.6 on 2019-10-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20191025_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cod_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Rol'),
        ),
    ]
