# Generated by Django 2.2.6 on 2019-11-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20191029_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fecha_mod',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
