# Generated by Django 2.2.6 on 2019-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20191103_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='id_lb',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
