# Generated by Django 2.2.6 on 2019-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_auto_20191104_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabase',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
