# Generated by Django 2.2.6 on 2019-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_lineabase_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permiso',
            field=models.CharField(max_length=100),
        ),
    ]
