# Generated by Django 2.2.6 on 2019-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_auto_20191108_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado'), ('F', 'Finalizado')], max_length=50),
        ),
    ]
