# Generated by Django 2.2.6 on 2019-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20191130_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado'), ('F', 'Finalizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lineabase',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado'), ('F', 'Finalizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fase',
            field=models.CharField(choices=[('A', 'Analisis'), ('D', 'Diseño'), ('D', 'Desarrollo'), ('M', 'Mantenimiento'), ('P', 'Prueba')], max_length=50),
        ),
    ]
