# Generated by Django 2.2.6 on 2019-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20191130_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=50),
        ),
    ]
