# Generated by Django 2.2.6 on 2019-12-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20191201_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fase',
            field=models.CharField(choices=[('Analisis', 'Analisis'), ('Diseño', 'Diseño'), ('Desarrollo', 'Desarrollo'), ('Mantenimiento', 'Mantenimiento'), ('Prueba', 'Prueba')], max_length=50),
        ),
    ]
